apiVersion: v1
kind: Secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJyZXBvc2l0b3J5Lm5leHRpdmEueHl6Ijp7InVzZXJuYW1lIjoiZG9ja2VyIiwicGFzc3dvcmQiOiIxcTJ3M2U0ciIsImVtYWlsIjoiZG9ja2VyQG5leHRpdmEuY29tIiwiYXV0aCI6IlpHOWphMlZ5T2pGeE1uY3paVFJ5In19
metadata:
  name: regsecret
